# agents/validation_agent.py
"""Agent for validating information provided by other agents."""

from typing import Any

from base.base_agent import BaseAgent


class ValidationAgent(BaseAgent):
    """An agent that validates and cross-references information from other agents."""

    def __init__(self, model: Any, **kwargs) -> None:
        # This agent does not use external tools
        super().__init__(model=model, tools=[], **kwargs)

    def _get_default_system_instruction(self) -> str:
        """Get the default system instruction for this agent.

        Returns:
            Default system instruction string.
        """
        return (
            "You are a fact-checker and validation expert. You will be given a statement "
            "generated by another agent. Your task is to analyze this statement for "
            "clarity, plausibility, and potential bias. Add a brief validation summary. "
            "For example, if the statement is 'The price of XYZ is $123', you could add "
            "'Validation: The price seems plausible for a tech stock. No issues detected.' "
            "Present the original content first, followed by your validation note."
        )