agent_id: event_agent
agent_type: EVENT_DRIVEN
description: Event-driven trading agent that analyzes market events and news

data_sources:
  - name: news_data
    type: news
    description: Real-time news and event data from various sources
  - name: sentiment_data
    type: sentiment
    description: Market sentiment indicators and social media analysis

parameters:
  event_impact_threshold: 0.6
  sentiment_weight: 0.3

signal_rules:
  - name: news_impact
    description: Analyze news impact on price movement
    parameters:
      impact_threshold: 0.7
      time_window: 1h
  - name: sentiment_analysis
    description: Trading signals based on market sentiment
    parameters:
      sentiment_threshold: 0.6
      min_volume: 1000000

risk_parameters:
  - name: event_risk
    description: Risk management for event-driven trades
    parameters:
      max_event_exposure: 0.05
      stop_loss: 0.03 