agent_id: technical_agent
agent_type: TECHNICAL
description: Technical analysis based trading agent using various technical indicators

data_sources:
  - name: technical_indicators
    type: technical
    description: Various technical indicators including RSI, MACD, Moving Averages

parameters:
  indicator_timeframes: ["1h", "4h", "1d"]
  signal_threshold: 0.8

signal_rules:
  - name: trend_following
    description: Follow trend based on moving averages
    parameters:
      ma_period: 20
      ma_type: EMA
  - name: momentum
    description: RSI based momentum signals
    parameters:
      rsi_period: 14
      overbought: 70
      oversold: 30

risk_parameters:
  - name: position_sizing
    description: Dynamic position sizing based on volatility
    parameters:
      vol_lookback: 20
      max_risk_per_trade: 0.02 